add knex
mishaqwerly/express-react-social-app pull request #5
Opened 2021-01-10 17:06 UTC by mishaqwerly

2021-01-11 19:42 UTC, ddavidov requested changes
Одна мелкая правка и можно сливать в мастер. В остальном - норм.

2021-01-11 19:42 UTC, ddavidov commented on api/.env
> +DB_NAME=test_bd
Неее) Этого в репозитории быть не должно. Этот файл нужно заигнорить в .gitignore

2021-01-11 19:42 UTC, ddavidov commented on api/package.json
> +    "nodemon": "^2.0.6",
nodemon лучше или глобально ставить или накрайняк как dev-dependencies, но то такое. сейчас уже можно и не исправлять.

2021-01-19 20:01 UTC, mishaqwerly commented on api/.env
> +DB_NAME=test_bd
исправил

2021-01-19 20:01 UTC, mishaqwerly commented on api/package.json
> +    "nodemon": "^2.0.6",
исправил

2021-01-19 20:01 UTC, merged